import os

rule all:
    input:
        storage.gcs("gs://bkt-dev-prj-dev-rfsci-bio-nonprt-posit-storage-bio/config_austin_slack.yaml")
    output:
        storage.gcs("gs://bkt-test-926/logs/test_gcs_snakemake.txt")
    shell:
        """
        cp {input} {output} 
        """



